[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "eduai-detector"
version = "0.1.0"
description = "AI text detection tool for educational use"
requires-python = ">=3.8"

[tool.setuptools]
package-dir = {"" = "src"}